// Generated by CoffeeScript 2.5.1
import Select from '@/components/descriptors/select';

import baseProps from '@/components/prop_types/base';

export default {
  vrfParent: 'Base',
  extends: Select,
  props: {
    ...baseProps,
    options: [Array, String],
    inverted: Boolean
  },
  data: function() {
    return {
      wrapper: {
        bitwiseValue: 0
      }
    };
  },
  created: function() {
    if (this.$originalValue == null) {
      return;
    }
    return this.wrapper.bitwiseValue = this.$originalValue;
  },
  watch: {
    'wrapper.bitwiseValue': function(value) {
      return this.$originalValue = value;
    },
    '$originalValue': function(value) {
      if (this.wrapper.bitwiseValue === value) {
        return;
      }
      return this.wrapper.bitwiseValue = parseInt(value) || 0;
    }
  }
};
