// Generated by CoffeeScript 2.5.1
import Base from '@/components/descriptors/base';

import baseProps from '@/components/prop_types/base';

export default {
  extends: Base,
  props: baseProps,
  computed: {
    date: function() {
      return this.VueResourceForm.dateInterceptor.out(this.$value);
    }
  },
  methods: {
    onInput: function(e) {
      return this.$value = this.VueResourceForm.dateInterceptor.in(e.target.value);
    }
  }
};
