// Generated by CoffeeScript 2.4.1
import BaseInput from '@/components/descriptors/base-input';

export default {
  extends: BaseInput,
  computed: {
    date: function() {
      return this.VueResourceForm.dateInterceptor.out(this.$value);
    }
  },
  methods: {
    onInput: function(e) {
      return this.$value = this.VueResourceForm.dateInterceptor.in(e.target.value);
    }
  }
};
