// Generated by CoffeeScript 2.5.1
import props from '@/components/prop_types/partial';

import Base from '@/components/descriptors/base';

import baseProps from '@/components/prop_types/base';

export default {
  extends: Base,
  props: {...baseProps, ...props},
  computed: {
    component: function() {
      var vue;
      vue = Object.getPrototypeOf(this.$root).constructor;
      return vue.prototype.VueResourceForm.partials[this.name];
    }
  }
};
