// Generated by CoffeeScript 2.5.1
import Base from '@/components/descriptors/base';

import baseProps from '@/components/prop_types/base';

export default {
  extends: Base,
  render: function() {
    var props, ref, ref1;
    props = {
      resource: this.$resource,
      resources: this.$sources,
      rootResource: this.$rootResource,
      rootResources: this.$rootResources,
      disabled: this.$formDisabled,
      tScope: this.tScope,
      t: this.t,
      errors: this.$errors,
      actionResults: this.$actionResults
    };
    return (ref = this.$scopedSlots) != null ? typeof ref.default === "function" ? (ref1 = ref.default(props)) != null ? ref1[0] : void 0 : void 0 : void 0;
  }
};
