// Generated by CoffeeScript 2.5.1
import Base from '@/components/descriptors/base';

export default {
  extends: Base,
  computed: {
    $disabled: function() {
      if (this.$readonly) {
        return true;
      }
      return this.$originalDisabled;
    },
    humanName: function() {
      return this.t('submit', '$vrf');
    }
  }
};
