// Generated by CoffeeScript 2.5.1
export default {
  name: {
    type: String,
    required: true
  },
  disabled: {
    type: [Boolean, String],
    default: void 0
  },
  readonly: {
    type: [Boolean, String],
    default: void 0
  },
  placeholder: {
    type: String
  },
  tabindex: {
    type: String
  },
  noLabel: Boolean,
  label: String,
  required: Boolean
};
