// Generated by CoffeeScript 2.5.1
export default {
  inverted: {
    type: Boolean,
    default: false
  },
  label: String,
  indeterminate: Boolean,
  noLabel: Boolean,
  power: [Number, String]
};
